# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# Multiple top-level headings in the same document
MD025: false
# Inline HTML
MD033: false
