# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# Multiple headings with the same content
MD024: false
# Multiple top-level headings in the same document
MD025: false
# Inline HTML
MD033: false
# Link text should be descriptive
MD059: false
